language: node_js
services: docker
node_js:
- node
branches:
  only:
  - master
before_install:
- npm install -g --silent @angular/cli
install:
- npm install
script:
- ng lint

deploy:
  provider: heroku
  api_key:
    secure: 1SJr19OFLWHzEhr//wUqhIV9hVMu9gDyd7Tsem4SuARFHItd7d6GN9Yd0LmD3l7pI4LWfMU4am4sFLMccUnLVHjTqSWacfKy5Vye1974frR/9MCtne6fOd/l3Py5L0RVAVMKEgCn0PqtpLvSmaTd85s1VG/XdNgzHHhtF3bijPhvAre0nrNFmbgRFqqHxl/v2A2S+atouoO/h8YyHcs2x2Z5ZiGEVAf+++UvsHakQ3UX4PV4aqSd54gzglaIR5Co9Nyq6ZAdYA2aME3odutRgglGS+K3fv/7oPtCDdolfAQO0+k6rLpfapSs1GP+UHGw/CLVR7O6ADdEHtbq0hlY4Kr/MDy5tLuwBGjFfEpNkLz7chR4ztNIDoBmFKVTlA0yk+WG7g4kcsMtqWN7XkrKUEPxazU9in3ZischmYuLJ1ubkJ/gZRH9mHm95Ekkw0WP8t9ZuveNTMv3Z3SbqtaQ0kPv8ZVHIs6kaL1gU9S0cbaa7p7B5jySj5QNHGejf90GbaAV52tg6AnF/9B6qIAQG6qBsUqCYp0UFV+TWCEMM2Hv7b6f3tsCOmfxrzDi41ogZK8x21zaU/HVki83i4MywGATo2E4cQaJtP4T13gQm7fEEUsmq+2viUckV/IknuqJ5nSbGsx07r0VXaAPo4kGqM3JfLAXRX0XA2tVN5Cm4+I=
  app: skill-ly-angular-app
